# Generated by Django 3.0.6 on 2020-05-25 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hogar', '0002_usuario_es_administrador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=50)),
                ('numero', models.IntegerField(default=0)),
                ('comuna', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='domicilio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hogar.Domicilio'),
        ),
    ]
