# Generated by Django 3.0.3 on 2020-05-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('complejidad', models.IntegerField(default=0)),
                ('duracion', models.IntegerField(default=0)),
                ('lugar', models.CharField(max_length=50)),
            ],
        ),
    ]
