# Generated by Django 3.0.7 on 2020-06-22 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hogar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('complejidad', models.PositiveIntegerField(default=0)),
                ('duracion', models.DurationField(default=0)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('comentarios', models.TextField(blank=True, max_length=200)),
                ('asignada', models.BooleanField(default=False)),
                ('completada', models.BooleanField(default=False)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hogar.Dependencia')),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hogar.Domicilio')),
            ],
        ),
        migrations.CreateModel(
            name='AsignarTarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.Tarea')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hogar.Usuario')),
            ],
        ),
    ]
