# Generated by Django 3.0.7 on 2020-06-30 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignartarea',
            old_name='candelarizada',
            new_name='calendarizar',
        ),
    ]
