# Generated by Django 3.0.8 on 2020-07-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='notifica_completada',
            field=models.BooleanField(default=False),
        ),
    ]
