# Generated by Django 3.0.8 on 2020-07-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_tarea_notifica_completada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='notifica_completada',
        ),
        migrations.AddField(
            model_name='asignartarea',
            name='notifica_completada',
            field=models.BooleanField(default=False),
        ),
    ]
