# Generated by Django 3.0.5 on 2020-05-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_tareas_encargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='comentario',
            field=models.TextField(default='null', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tareas',
            name='lugar',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
