# Generated by Django 3.0.6 on 2020-05-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_auto_20200528_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareas',
            name='comentario',
        ),
        migrations.AlterField(
            model_name='tareas',
            name='lugar',
            field=models.CharField(max_length=50),
        ),
    ]
