# Generated by Django 3.0.5 on 2020-05-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_auto_20200528_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareas',
            name='comentario',
        ),
        migrations.AddField(
            model_name='tareas',
            name='comentarios',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tareas',
            name='completada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='lugar',
            field=models.CharField(max_length=50),
        ),
    ]
