# Generated by Django 3.0.5 on 2020-05-29 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_auto_20200528_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
