# Generated by Django 3.0.7 on 2020-06-30 00:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=100)),
                ('type', models.CharField(blank=True, default='EV', max_length=10, null=True)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(default=django.utils.timezone.now)),
                ('asignar_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.AsignarTarea')),
            ],
        ),
    ]
