# Generated by Django 3.0.7 on 2020-07-05 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almanac_calendar', '0001_initial'),
        ('tareas', '0001_initial'),
        ('hogar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario_ocupado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hogar.Usuario'),
        ),
        migrations.AddField(
            model_name='event',
            name='asignar_tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.AsignarTarea'),
        ),
    ]
