# Generated by Django 3.0.5 on 2020-06-23 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almanac_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
