# Generated by Django 3.0.7 on 2020-07-04 17:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hogar', '0001_initial'),
        ('almanac_calendar', '0002_event_asignar_tarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario_Ocupado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(default=django.utils.timezone.now)),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
                ('repetir', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hogar.Usuario')),
            ],
        ),
    ]
