# Generated by Django 3.0.5 on 2020-06-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almanac_calendar', '0002_auto_20200622_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateField(auto_now_add=True),
        ),
    ]
