# Generated by Django 3.0.5 on 2020-06-30 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hogar', '0001_initial'),
        ('almanac_calendar', '0007_auto_20200628_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hogar.Usuario'),
        ),
    ]
