# Generated by Django 3.0.5 on 2020-06-30 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almanac_calendar', '0008_event_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='type',
        ),
    ]
